POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QwMEBleGFtcGxlLmNvbSIsImV4cCI6MTcwODM0Njg0MiwidXNlcl9pZCI6MX0.9AuWqRGbcKY4lGJ1WhiUlB07CC-qQ2Z7D0EJEyZpNBE

{
  "title" : "test event 0001",
  "description" : "test description 0000",
  "location" : "test location 0000",
  "dateTime" : "2999-12-31T23:59:59Z"
}
