POST http://localhost:8080/events
content-type: application/json
# authorization: 

{
  "title" : "test event 0000",
  "description" : "test description 0000",
  "location" : "test location 0000",
  "dateTime" : "2999-12-31T23:59:59Z"
}
