PUT http://localhost:8080/events/1
content-type: application/json 
# Authorization:

{
    "Title": "updated event",
    "Description": "This is an updated event",
    "Location": "new location",
    "DateTime": "2099-12-31T23:59:59Z"

}