PUT http://localhost:8080/events/2
content-type: application/json 
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QwMEBleGFtcGxlLmNvbSIsImV4cCI6MTcwNzkxMzQ5NiwidXNlcl9pZCI6MX0.qT9ec_Je63h5AgdbgMfgrplCW-5G7wdI2PIl6vzs2IE

{
    "Title": "updated event",
    "Description": "This is an updated event",
    "Location": "new location",
    "DateTime": "2099-12-31T23:59:59Z"

}